name: Run Kraken Test - Ghost 4.5

on:
  workflow_dispatch:
    inputs:
      ghost_version_v4: # Nombre de input diferente para evitar conflictos si se usa en el mismo repo
        description: 'Ghost version (v4.x.x)'
        required: true
        default: '4.5'

jobs:
  run-kraken-ghost-v4:
    runs-on: ubuntu-22.04 # Especificar Ubuntu 22.04 

    env:
      PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome-stable
      PUPPETEER_LAUNCH_ARGS: "--no-sandbox --disable-setuid-sandbox --disable-dev-shm-usage --remote-debugging-port=9222"
      NODE_ENV: production 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 14.x
        uses: actions/setup-node@v4
        with:
          node-version: '14.x' # Node.js 14.x para Ghost 4.5.0

      - name: Install system dependencies for Ubuntu 20.04
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            google-chrome-stable \
            xvfb \
            curl \
            wget \
            gnupg \
            unzip \
            sudo \
            libnss3 \
            libatk-bridge2.0-0 \
            libxss1 \
            libgbm1 \
            libasound2 \ # Para Ubuntu 20.04, libasound2 es correcto
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            libgtk-3-0 \
            libdrm2 \
            libu2f-udev \
            fonts-liberation \
            libappindicator3-1 \
            ca-certificates \
            apt-transport-https \
            android-tools-adb
          echo "Chrome version: $(google-chrome-stable --version)"
          echo "Node version: $(node -v)"
          echo "NPM version: $(npm -v)"
          echo "ADB version: $(adb version || echo 'adb not found after install attempt')"

      - name: Install compatible Ghost CLI for Ghost 4.x
        # Ghost-CLI 1.21.0 es la última versión que soporta Node 14.
        run: sudo npm install -g ghost-cli@1.21.0 && ghost --version

      - name: Create Ghost working dir (v4)
        run: mkdir -p ${{ github.workspace }}/ghost-instance-v4 # Directorio con nombre diferente

      - name: Set up Ghost 4.x instance
        working-directory: ${{ github.workspace }}/ghost-instance-v4
        run: |
          echo "Instalando Ghost versión: ${{ github.event.inputs.ghost_version_v4 }}"
          ghost install ${{ github.event.inputs.ghost_version_v4 }} \
            --force \
            --no-prompt \
            --no-start \
            --local \
            --db sqlite3 \
            --no-setup-linux-user \
            --dir ${{ github.workspace }}/ghost-instance-v4 \
            --process local
          echo "Iniciando Ghost..."
          ghost start --no-enable-stackdriver

      - name: Wait for Ghost 4.x to be ready
        working-directory: ${{ github.workspace }}/ghost-instance-v4
        run: |
          echo "Esperando que Ghost (v4) esté listo..."
          for i in {1..30}; do 
            if curl -s --fail http://localhost:2368/ghost/ > /dev/null; then
              echo "Ghost (v4) está listo!"
              exit 0
            fi
            echo "Intento $i: Ghost (v4) no está listo aún..."
            sleep 5
          done
          echo "Error: Ghost (v4) no inició a tiempo."
          echo "Mostrando logs de Ghost (v4):"
          ghost log -e production # Asumiendo que NODE_ENV=production se propaga
          exit 1
      
      # Instalar dependencias del proyecto (Kraken) desde la raíz
      # Siguiendo la lógica del Dockerfile para Ghost v4:
      # 1. npm install (usa package.json raíz, puede crear/actualizar package-lock.json)
      # 2. npm install <paquetes_especificos_kraken>
      - name: Install Project (Kraken) dependencies for Node 14
        # No se usa --prefix, opera en la raíz del checkout
        run: |
          echo "Instalando dependencias del proyecto desde la raíz con Node.js $(node -v) y npm $(npm -v)..."
          # Opcional: rm -f package-lock.json # Si quieres forzar una resolución fresca como sugiere el comentario en tu Dockerfile
          npm install
          echo "Instalando/actualizando paquetes específicos de Kraken..."
          # Usamos las versiones de tu e2e/misw-4103-kraken/package.json como referencia
          npm install @cucumber/cucumber@7.2.1 kraken-node@^1.0.24
        # ¡IMPORTANTE! Esto modificará node_modules en la raíz.
        # Si tu package.json raíz ya tiene estas dependencias con estas versiones,
        # el segundo `npm install` podría ser redundante o solo verificar.

      - name: Debug Project node_modules contents (root)
        if: always()
        run: |
          echo "Current directory for debug: $(pwd)"
          echo "---------------------------------------------------------------------"
          echo "Listando contenido de ./node_modules/ (raíz):"
          ls -la ./node_modules/ || echo "./node_modules/ (raíz) no encontrada o vacía"
          echo "---------------------------------------------------------------------"
          echo "Listando contenido de ./node_modules/.bin/ (raíz):"
          ls -la ./node_modules/.bin/ || echo "./node_modules/.bin/ (raíz) no encontrada o vacía"
          echo "---------------------------------------------------------------------"
        continue-on-error: true

      - name: Run Kraken tests against Ghost 4.x
        # Se asume que el script para correr Kraken está en el package.json de la RAÍZ
        # y que este script llama a `node e2e/misw-4103-kraken/krakenRunner.js`
        run: |
          echo "Directorio de trabajo actual para pruebas de Kraken: $(pwd)"
          # Asegurar que las carpetas para los resultados existan, relativas a la raíz del workspace
          mkdir -p ${{ github.workspace }}/e2e/misw-4103-kraken/screenshots 
          mkdir -p ${{ github.workspace }}/e2e/misw-4103-kraken/reports
          xvfb-run -a --server-args="-screen 0 1280x1024x24" npm run test:base 

      - name: List files in screenshots directory (for upload verification)
        if: always()
        run: |
          echo "Verificando contenido para upload-artifact en e2e/misw-4103-kraken/screenshots"
          ls -R ${{ github.workspace }}/e2e/misw-4103-kraken/screenshots || echo "Carpeta screenshots no encontrada o vacía"

      - name: Upload Kraken screenshots (Ghost v4 run)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: kraken-screenshots-ghost-v4
          path: ${{ github.workspace }}/e2e/misw-4103-kraken/screenshots/

      - name: Upload test report (Ghost v4 run)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report-ghost-v4
          path: ${{ github.workspace }}/e2e/misw-4103-kraken/reports/

      - name: Teardown Ghost 4.x
        if: always()
        run: |
          GHOST_DIR_V4="${{ github.workspace }}/ghost-instance-v4"
          if [ -d "$GHOST_DIR_V4" ]; then
            echo "Attempting to stop Ghost (v4) in $GHOST_DIR_V4"
            (cd "$GHOST_DIR_V4" && ghost stop) || echo "Ghost stop (v4) failed or Ghost was not running/dir was not a Ghost instance."
          else
            echo "Ghost instance directory $GHOST_DIR_V4 not found, skipping teardown."
          fi